"""Local web interface for ROBERTA — Verified On-Chain Intelligence."""

from __future__ import annotations

ROBERTA_WEB_UI_HTML = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="color-scheme" content="dark">
<title>ROBERTA — Verified On-Chain Intelligence</title>
<style>
:root{--bg:#07090d;--panel:#0f141b;--panel2:#151c25;--line:#26303c;--text:#f4f7fa;--muted:#98a5b5;--mint:#8af0c5;--blue:#7aabff;--amber:#ffd27a;--red:#ff9292}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(circle at 15% 0,rgba(122,171,255,.11),transparent 30rem),radial-gradient(circle at 90% 0,rgba(138,240,197,.08),transparent 30rem),var(--bg);color:var(--text);font:14px/1.5 Inter,system-ui,-apple-system,Segoe UI,sans-serif}
button,input,select,textarea{font:inherit}.app{min-height:100vh;display:grid;grid-template-columns:240px 1fr}.side{position:sticky;top:0;height:100vh;padding:24px 17px;border-right:1px solid var(--line);background:rgba(7,9,13,.88);backdrop-filter:blur(16px);display:flex;flex-direction:column}.brand{display:flex;gap:11px;align-items:center}.logo{width:42px;height:42px;border:1px solid var(--line);border-radius:13px;display:grid;place-items:center;background:linear-gradient(145deg,rgba(138,240,197,.15),rgba(122,171,255,.10));font-weight:900;color:var(--mint)}.brand b{display:block;letter-spacing:.05em}.brand small{color:var(--muted)}nav{display:grid;gap:7px;margin-top:28px}nav button{border:0;background:transparent;color:var(--muted);text-align:left;padding:10px 12px;border-radius:10px;cursor:pointer}nav button:hover{background:var(--panel2);color:var(--text)}.trust{margin-top:auto;padding:13px;border:1px solid var(--line);border-radius:14px;background:var(--panel);color:var(--muted);font-size:12px}.trust b{color:#cdd6e0}
.main{min-width:0}.top{position:sticky;top:0;z-index:10;padding:13px 22px;border-bottom:1px solid var(--line);background:rgba(7,9,13,.8);backdrop-filter:blur(16px);display:flex;justify-content:space-between;gap:10px;align-items:center}.pills{display:flex;gap:8px;flex-wrap:wrap}.pill{border:1px solid var(--line);background:var(--panel);border-radius:999px;padding:7px 10px;color:var(--muted);font-size:12px}.dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#777;margin-right:7px}.online .dot{background:var(--mint);box-shadow:0 0 13px rgba(138,240,197,.7)}.offline .dot{background:var(--red)}.btn{border:1px solid var(--line);background:var(--panel);color:var(--text);padding:9px 12px;border-radius:10px;cursor:pointer}.btn:hover{background:var(--panel2)}.primary{border-color:transparent;background:var(--mint);color:#06100c;font-weight:800}.wrap{max-width:1480px;margin:auto;padding:28px 27px 60px}
.hero{display:grid;grid-template-columns:1.45fr .75fr;gap:14px}.card{border:1px solid var(--line);background:linear-gradient(145deg,rgba(21,28,37,.9),rgba(15,20,27,.95));border-radius:18px}.heroMain{padding:27px;min-height:225px}.eyebrow{color:var(--mint);font-size:11px;font-weight:900;letter-spacing:.13em;text-transform:uppercase}h1{font-size:clamp(31px,4vw,53px);line-height:1.03;letter-spacing:-.045em;margin:11px 0}.lead{color:var(--muted);max-width:760px}.heroBtns{display:flex;gap:9px;flex-wrap:wrap;margin-top:21px}.state{padding:19px}.state h3{margin:0 0 12px}.state div{color:var(--muted);font-size:12px;padding:9px 0;border-top:1px solid var(--line)}.state div:first-of-type{border-top:0}.state strong{color:var(--mint)}
.head{display:flex;justify-content:space-between;gap:15px;align-items:end;margin:31px 0 13px}.head h2{margin:0;font-size:21px}.head p{margin:4px 0 0;color:var(--muted);font-size:12px}.search{width:min(340px,100%)}.search input{width:100%;border:1px solid var(--line);background:var(--panel);color:var(--text);padding:10px 12px;border-radius:10px;outline:none}.filters{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:13px}.filter{border:1px solid var(--line);background:var(--panel);color:var(--muted);border-radius:999px;padding:6px 9px;cursor:pointer;font-size:11px}.filter.active{background:var(--mint);color:#06100c;border-color:transparent;font-weight:800}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:11px}.svc{border:1px solid var(--line);background:var(--panel);border-radius:15px;padding:15px;min-height:185px;display:flex;flex-direction:column;transition:.16s}.svc:hover{transform:translateY(-2px);background:var(--panel2)}.svcTop{display:flex;justify-content:space-between}.ico{width:37px;height:37px;border-radius:11px;background:#1c2530;display:grid;place-items:center}.tag{border:1px solid var(--line);border-radius:999px;padding:4px 7px;color:var(--mint);font-size:9px;height:max-content}.tag.advanced{color:var(--amber)}.svc h3{font-size:14px;margin:13px 0 6px}.svc p{font-size:11.5px;color:var(--muted);margin:0}.svcFoot{margin-top:auto;padding-top:12px;display:flex;justify-content:space-between;align-items:center;color:var(--muted);font-size:9px}.run{border:0;background:transparent;color:var(--mint);font-weight:800;cursor:pointer}
.chatLayout{display:grid;grid-template-columns:1fr 310px;gap:12px}.chat,.info{border:1px solid var(--line);background:var(--panel);border-radius:17px;overflow:hidden}.chatHead{padding:14px 15px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between}.messages{height:480px;overflow:auto;padding:17px;display:flex;flex-direction:column;gap:11px}.msg{max-width:88%;padding:11px 13px;border-radius:13px;white-space:pre-wrap;word-break:break-word}.msg.user{align-self:flex-end;background:#eafff5;color:#06100c}.msg.assistant{align-self:flex-start;background:var(--panel2);border:1px solid var(--line);color:#d5dde6}.msg.system{align-self:center;color:var(--muted);font-size:11px;padding:3px}.composer{border-top:1px solid var(--line);padding:12px;display:grid;grid-template-columns:1fr auto;gap:8px}.composer textarea{resize:none;min-height:46px;max-height:130px;border:1px solid var(--line);background:var(--panel2);color:var(--text);border-radius:11px;padding:11px;outline:none}.info{padding:15px}.info h3{margin:0 0 10px}.infoBlock{border-top:1px solid var(--line);padding:11px 0}.infoBlock:first-of-type{border-top:0}.infoBlock b{display:block;color:#cdd6e0;font-size:10px;text-transform:uppercase;letter-spacing:.1em;margin-bottom:4px}.infoBlock span{color:var(--muted);font-size:11px}
.modalBg{display:none;position:fixed;inset:0;z-index:50;background:rgba(0,0,0,.7);padding:18px;place-items:center}.modalBg.open{display:grid}.modal{width:min(610px,100%);max-height:90vh;overflow:auto;background:#0d1218;border:1px solid #34404e;border-radius:18px}.modalHead{padding:18px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:12px}.modalHead h3{margin:0}.modalHead p{color:var(--muted);font-size:11px;margin:5px 0 0}.close{width:32px;height:32px;border:0;border-radius:9px;background:var(--panel2);color:var(--text);cursor:pointer}.form{padding:17px;display:grid;gap:13px}.field{display:grid;gap:6px}.field label{color:#cbd4df;font-size:11px;font-weight:700}.field input,.field select{border:1px solid var(--line);background:var(--panel);color:var(--text);padding:10px 11px;border-radius:10px;outline:none}.modalActions{padding:0 17px 17px;display:flex;justify-content:flex-end;gap:8px}.settings{display:none;position:fixed;z-index:40;right:18px;top:62px;width:min(380px,calc(100vw - 36px));background:#0d1218;border:1px solid #34404e;border-radius:15px;padding:15px}.settings.open{display:block}.settings h3{margin:0 0 11px}.settings .field+.field{margin-top:10px}.note{color:var(--muted);font-size:10px;margin-top:9px}
@media(max-width:1160px){.grid{grid-template-columns:repeat(3,1fr)}.hero{grid-template-columns:1fr}.chatLayout{grid-template-columns:1fr}.info{display:none}}@media(max-width:820px){.app{grid-template-columns:1fr}.side{display:none}.wrap{padding:20px 15px 50px}.top{padding:11px 14px}.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:540px){.grid{grid-template-columns:1fr}.head{align-items:stretch;flex-direction:column}.search{width:100%}.composer{grid-template-columns:1fr}.heroBtns{display:grid}.heroBtns button{width:100%}}
</style>
</head>
<body>
<div class="app">
<aside class="side">
  <div class="brand"><div class="logo">R</div><div><b>ROBERTA</b><small>Verified On-Chain Intelligence</small></div></div>
  <nav><button data-go="home">Overview</button><button data-go="services">Services</button><button data-go="chat">Ask Roberta</button><button data-svc="key">Status Key</button></nav>
  <div class="trust"><b>Authority path</b><br>User → ROBERTA → Chain Scout → CMIS → verified provider/source.<br><br>Analysis only. Execution remains unauthorized.</div>
</aside>
<main class="main">
<header class="top">
  <div class="pills"><div id="health" class="pill"><span class="dot"></span>Checking ROBERTA…</div><div class="pill">CMIS 1.18</div></div>
  <div><button class="btn" id="settingsBtn">Connection</button></div>
</header>
<div id="settings" class="settings">
  <h3>Connection</h3>
  <div class="field"><label>ROBERTA bridge URL</label><input id="apiBase" placeholder="Same origin"></div>
  <div class="field"><label>Bearer token (if configured)</label><input id="apiKey" type="password" autocomplete="off" placeholder="ROBERTA_API_KEY"></div>
  <div class="note">Connection values stay in this browser tab only. Default loopback use needs no token.</div>
</div>
<div class="wrap">
<section id="home" class="hero">
  <div class="card heroMain"><div class="eyebrow">X1-first verified intelligence</div><h1>One place for every accepted ROBERTA service.</h1><div class="lead">Market, risk, tokenomics, history, burn, discovery, concentration, evidence and pre-trade analysis—through the same ROBERTA → Scout → CMIS trust path.</div><div class="heroBtns"><button class="btn primary" data-svc="full">Run Full Assessment</button><button class="btn" data-svc="scan">Instant X1 Scan</button><button class="btn" data-go="chat">Ask a Question</button></div></div>
  <div class="card state"><h3>Current product state</h3><div><strong>Accepted:</strong> Instant X1 Scan v3, Burn, Discovery, What Changed, Compare and current-market freshness.</div><div><strong>Accepted:</strong> CMIS 1.18 pull-only Concentration Warning through ROBERTA.</div><div><strong>Not promoted:</strong> Warp / bridge-flow intelligence remains evidence-gated and is not presented as runnable.</div><div><strong>Boundary:</strong> Website actions never call CMIS directly.</div></div>
</section>
<section id="services">
  <div class="head"><div><h2>Services</h2><p>Available services match the accepted repository state. Advanced evidence-gated inputs are labeled.</p></div><div class="search"><input id="search" type="search" placeholder="Search services…"></div></div>
  <div id="filters" class="filters"></div><div id="grid" class="grid"></div>
</section>
<section id="chat">
  <div class="head"><div><h2>Ask ROBERTA</h2><p>Normal-language access to the same verified intelligence core.</p></div></div>
  <div class="chatLayout"><div class="chat"><div class="chatHead"><div><b>ROBERTA</b><div style="color:var(--muted);font-size:10px">Verified On-Chain Intelligence</div></div><span class="tag">Analysis only</span></div><div id="messages" class="messages"><div class="msg assistant">I’m ready. Choose a service above or ask a normal question about X1 market conditions, risk, tokenomics, history, burns, discovery, concentration, evidence, or pre-trade analysis.</div></div><div class="composer"><textarea id="composer" rows="1" placeholder="Ask ROBERTA…"></textarea><button id="send" class="btn primary">Send</button></div></div>
  <aside class="info"><h3>Trust model</h3><div class="infoBlock"><b>Fresh facts</b><span>Accepted CMIS/provider evidence overrides remembered or learned live values.</span></div><div class="infoBlock"><b>Unknowns</b><span>Missing evidence stays UNKNOWN / UNAVAILABLE. It is never zero-filled.</span></div><div class="infoBlock"><b>Proof vs risk</b><span>Evidence quality is separate from deterministic risk. Strong proof may support WARN or BLOCK.</span></div><div class="infoBlock"><b>Execution</b><span>No result authorizes signing, broadcast, custody, swaps, bridge transfers, or autonomous value movement.</span></div></aside>
  </div>
</section>
</div>
</main>
</div>
<div id="modalBg" class="modalBg"><div class="modal"><div class="modalHead"><div><h3 id="modalTitle"></h3><p id="modalDesc"></p></div><button id="close" class="close">×</button></div><form id="serviceForm"><div id="formFields" class="form"></div><div class="modalActions"><button id="cancel" type="button" class="btn">Cancel</button><button type="submit" class="btn primary">Send to ROBERTA</button></div></form></div></div>
<script>
var services=[
{id:'scan',name:'Instant X1 Scan',icon:'⚡',cat:'Core',status:'Available',desc:'Accepted X1 scan covering identity, market, tokenomics, history, risk, evidence quality and field-scoped freshness.',fields:[['asset','Asset / mint','text','e.g. AGI']],prompt:function(v){return 'Run an Instant X1 Scan for '+v.asset+'. Use X1 Scout and the accepted instant_x1_scan/v3 path. Keep proof separate from risk and show unavailable fields.'}},
{id:'overview',name:'Asset Overview',icon:'◈',cat:'Core',status:'Available',desc:'Verified current snapshot and asset context with explicit limitations.',fields:[['asset','Asset / mint','text','e.g. XNT']],prompt:function(v){return 'Give me the ROBERTA asset overview for '+v.asset+'. Route through the appropriate Scout and CMIS; do not estimate missing values.'}},
{id:'compare',name:'Compare Two Assets',icon:'⇄',cat:'Market',status:'Available',desc:'Current and overlapping-history comparison without recomputing accepted facts outside CMIS.',fields:[['asset1','First asset','text','e.g. XNT'],['asset2','Second asset','text','e.g. AGI']],prompt:function(v){return 'Compare '+v.asset1+' and '+v.asset2+' through ROBERTA. Use accepted CMIS comparison and history services. Keep unavailable or non-comparable metrics explicit.'}},
{id:'risk',name:'Risk Assessment',icon:'◇',cat:'Risk',status:'Available',desc:'Deterministic CMIS risk result with exact reasons and evidence limitations.',fields:[['asset','Asset / mint','text','e.g. AGI']],prompt:function(v){return 'Run a deterministic ROBERTA risk assessment for '+v.asset+'. Preserve the exact CMIS risk result, reasons, proof status and missing evidence.'}},
{id:'tokenomics',name:'Tokenomics & Authorities',icon:'◎',cat:'Asset',status:'Available',desc:'Supply, mint/freeze authority and other structural token facts where verified.',fields:[['asset','Asset / mint','text','e.g. AGI']],prompt:function(v){return 'Analyze tokenomics and authorities for '+v.asset+' through ROBERTA and CMIS. Distinguish verified, provider-reported and unavailable fields.'}},
{id:'liquidity',name:'Liquidity Analysis',icon:'≈',cat:'Market',status:'Available',desc:'Liquidity structure and supported pool/route evidence with exact scope.',fields:[['asset','Asset / mint','text','e.g. XNT']],prompt:function(v){return 'Run ROBERTA liquidity analysis for '+v.asset+'. Show verified liquidity, pool structure, evidence scope, freshness and limitations.'}},
{id:'history',name:'Historical Analysis',icon:'◷',cat:'History',status:'Available',desc:'Verified windows and all-available observations with explicit gaps and lifetime limits.',fields:[['asset','Asset / mint','text','e.g. AGI']],prompt:function(v){return 'Run ROBERTA historical analysis for '+v.asset+'. Use accepted CMIS history and all-available observations when useful. Do not imply continuous or lifetime coverage unless verified.'}},
{id:'activity',name:'Market Activity',icon:'⌁',cat:'Market',status:'Available',desc:'Bounded transaction and market-activity observations where accepted evidence supports them.',fields:[['asset','Asset / mint','text','e.g. AGI']],prompt:function(v){return 'Show verified market activity for '+v.asset+' through ROBERTA. Preserve the exact scope and freshness of the activity evidence.'}},
{id:'concentration',name:'Concentration Change',icon:'◉',cat:'Intelligence',status:'Advanced',desc:'CMIS-owned concentration-change intelligence by evidence ID; concentration is not beneficial ownership.',fields:[['asset','Asset / mint','text','e.g. AGI'],['evidence','Intelligence evidence ID','text','ie_…']],prompt:function(v){return 'Run ROBERTA concentration change intelligence for '+v.asset+' using CMIS intelligence evidence id '+v.evidence+'. Do not infer beneficial ownership, intent, fraud, manipulation or risk from concentration alone.'}},
{id:'warning',name:'Concentration Warning',icon:'!',cat:'Intelligence',status:'Advanced',desc:'CMIS 1.18 pull-only WATCH/CLEAR warning. Push delivery remains unauthorized.',fields:[['asset','Asset / mint','text','e.g. AGI']],prompt:function(v){return 'Check the current pull-only concentration warning intelligence for '+v.asset+' through ROBERTA using accepted CMIS 1.18 concentration_warning_intelligence/v1. If required CMIS-owned evidence ids or persistence inputs are unavailable, state exactly what is missing. Keep WATCH/CLEAR separate from risk.'}},
{id:'rank',name:'Rank X1 Assets',icon:'≋',cat:'Market',status:'Available',desc:'Rank X1 assets across the bounded XDEX universe by an accepted metric.',fields:[['metric','Metric','select','liquidity|volume|activity'],['limit','Result limit','number','10']],prompt:function(v){return 'Rank X1 assets by '+v.metric+' and return the top '+(v.limit||10)+' through ROBERTA. Preserve universe and scope limits and do not fabricate missing metrics.'}},
{id:'pretrade',name:'Pre-Trade Analysis',icon:'↗',cat:'Risk',status:'Available',desc:'Read-only requested-size analysis using verified liquidity and route facts where supported.',fields:[['asset','Asset / mint','text','e.g. AGI'],['side','Side','select','BUY|SELL'],['usd','USD amount','number','500']],prompt:function(v){return 'Run a ROBERTA pre-trade analysis for a '+v.side+' of '+v.asset+' with requested notional $'+v.usd+'. Use accepted CMIS pre_trade_check. Explain trade-size and liquidity constraints plus missing evidence. Analysis only; no execution.'}},
{id:'evidence',name:'Evidence Quality Report',icon:'✓',cat:'Evidence',status:'Available',desc:'Provenance, verification, freshness, conflicts, Proof Score and unresolved fields.',fields:[['asset','Asset / mint','text','e.g. AGI']],prompt:function(v){return 'Give me an evidence quality report for '+v.asset+' through ROBERTA. Focus on provenance, verification, freshness, conflicts, Proof Score, scope and unresolved fields. Do not equate proof strength with safety.'}},
{id:'burn',name:'Burn Intelligence',icon:'△',cat:'Intelligence',status:'Available',desc:'Verified observed cumulative burn plus 1h / 24h / 7d / 30d windows and supported comparisons.',fields:[['asset','Asset / mint','text','e.g. AGI']],prompt:function(v){return 'Run ROBERTA Burn Intelligence for '+v.asset+'. Show verified observed cumulative burn, 1h/24h/7d/30d windows, event counts and supported period-over-period changes. Distinguish observed coverage from complete lifetime burn.'}},
{id:'discovery',name:'Discovery Intelligence',icon:'⌖',cat:'Intelligence',status:'Available',desc:'First and latest verified observations, counts, coverage bounds and elapsed observed history.',fields:[['asset','Asset / mint','text','e.g. AGI']],prompt:function(v){return 'Run ROBERTA Discovery Intelligence for '+v.asset+'. Show first and latest verified observations, observation count, coverage bounds and elapsed observed history. Do not relabel first observation as token launch or inception.'}},
{id:'changed',name:'What Changed?',icon:'Δ',cat:'History',status:'Available',desc:'Change summary from accepted current/history evidence without invented deltas or causal claims.',fields:[['asset','Asset / mint','text','e.g. AGI']],prompt:function(v){return 'Tell me what changed for '+v.asset+' using ROBERTA\'s accepted What Changed workflow. Use verified current and historical evidence only and do not invent causes.'}},
{id:'full',name:'Full Assessment',icon:'▣',cat:'Core',status:'Available',desc:'Broad assessment combining relevant accepted market, risk, tokenomics, history and evidence services.',fields:[['asset','Asset / mint','text','e.g. AGI']],prompt:function(v){return 'Run a full ROBERTA assessment for '+v.asset+'. Use relevant accepted Scout -> CMIS services, preserve unknowns and limitations, and give the answer first with evidence underneath.'}},
{id:'key',name:'Alert & Status Key',icon:'?',cat:'Evidence',status:'Available',desc:'Explains risk, CMIS status, verification, proof strength, freshness and execution labels.',fields:[],prompt:function(){return 'Show me ROBERTA\'s alert and status key, including risk, CMIS status, verification, proof strength, freshness, common warnings and execution meaning.'}},
{id:'chat',name:'Ask Anything',icon:'✦',cat:'Core',status:'Available',desc:'Normal question; ROBERTA selects the appropriate specialist and verified-data path.',fields:[['question','Question','text','e.g. Is AGI getting stronger?']],prompt:function(v){return v.question}}
];
var cats=['All','Core','Market','Risk','Asset','History','Intelligence','Evidence'],activeCat='All',activeService=null,sending=false;
function el(s){return document.querySelector(s)}function base(){return(el('#apiBase').value||'').trim().replace(/\/$/,'')}function url(p){return base()?base()+p:p}function headers(){var h={'Content-Type':'application/json'},k=el('#apiKey').value.trim();if(k)h.Authorization='Bearer '+k;return h}
function renderFilters(){el('#filters').innerHTML=cats.map(function(c){return '<button class="filter '+(c===activeCat?'active':'')+'" data-cat="'+c+'">'+c+'</button>'}).join('')}
function render(){var q=el('#search').value.trim().toLowerCase(),list=services.filter(function(s){return(activeCat==='All'||s.cat===activeCat)&&(!q||(s.name+' '+s.desc+' '+s.cat).toLowerCase().indexOf(q)>=0)});el('#grid').innerHTML=list.map(function(s){return '<article class="svc"><div class="svcTop"><div class="ico">'+s.icon+'</div><span class="tag '+(s.status==='Advanced'?'advanced':'')+'">'+s.status+'</span></div><h3>'+s.name+'</h3><p>'+s.desc+'</p><div class="svcFoot"><span>X1 · Read-only</span><button class="run" data-svc="'+s.id+'">Run →</button></div></article>'}).join('')||'<div style="color:var(--muted)">No matching services.</div>'}
function field(f){var n=f[0],l=f[1],t=f[2],p=f[3];if(t==='select'){return '<div class="field"><label>'+l+'</label><select name="'+n+'" required>'+p.split('|').map(function(x){return '<option value="'+x+'">'+x+'</option>'}).join('')+'</select></div>'}return '<div class="field"><label>'+l+'</label><input name="'+n+'" type="'+t+'" placeholder="'+p+'" required '+(t==='number'?'min="0" step="any"':'')+'></div>'}
function openSvc(id){activeService=services.find(function(s){return s.id===id});if(!activeService)return;el('#modalTitle').textContent=activeService.name;el('#modalDesc').textContent=activeService.desc;el('#formFields').innerHTML=activeService.fields.length?activeService.fields.map(field).join(''):'<div style="color:var(--muted)">No additional input is required.</div>';el('#modalBg').classList.add('open')}
function closeSvc(){el('#modalBg').classList.remove('open');activeService=null}
function msg(role,text){var d=document.createElement('div');d.className='msg '+role;d.textContent=text;el('#messages').appendChild(d);el('#messages').scrollTop=el('#messages').scrollHeight;return d}
function busy(v){sending=v;el('#send').disabled=v;el('#send').textContent=v?'Working…':'Send'}
async function health(){var h=el('#health');try{var r=await fetch(url('/healthz'));var d=await r.json();if(r.ok&&d.status==='ok'){h.className='pill online';h.innerHTML='<span class="dot"></span>ROBERTA online';return}throw 0}catch(e){h.className='pill offline';h.innerHTML='<span class="dot"></span>ROBERTA offline'}}
async function send(text){text=(text||'').trim();if(!text||sending)return;msg('user',text);el('#composer').value='';busy(true);var wait=msg('system','ROBERTA is checking accepted evidence…');try{var r=await fetch(url('/v1/roberta'),{method:'POST',headers:headers(),body:JSON.stringify({message:text})}),d=await r.json().catch(function(){return{}});wait.remove();if(!r.ok)msg('assistant',(d.error&&d.error.message)||('Request failed ('+r.status+')'));else msg('assistant',d.reply||'ROBERTA returned no reply.')}catch(e){wait.remove();msg('assistant','I could not reach the ROBERTA bridge. Verify that it is running and check Connection settings.')}finally{busy(false);health()}}
renderFilters();render();health();setInterval(health,30000);
document.addEventListener('click',function(e){var s=e.target.closest('[data-svc]');if(s)openSvc(s.dataset.svc);var g=e.target.closest('[data-go]');if(g)document.getElementById(g.dataset.go).scrollIntoView({behavior:'smooth'});var c=e.target.closest('[data-cat]');if(c){activeCat=c.dataset.cat;renderFilters();render()}});
el('#search').addEventListener('input',render);el('#close').onclick=closeSvc;el('#cancel').onclick=closeSvc;el('#modalBg').addEventListener('click',function(e){if(e.target===el('#modalBg'))closeSvc()});
el('#serviceForm').addEventListener('submit',function(e){e.preventDefault();if(!activeService)return;var data=Object.fromEntries(new FormData(e.currentTarget).entries()),p=activeService.prompt(data);closeSvc();document.getElementById('chat').scrollIntoView({behavior:'smooth'});send(p)});
el('#send').onclick=function(){send(el('#composer').value)};el('#composer').addEventListener('keydown',function(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send(el('#composer').value)}});
el('#settingsBtn').onclick=function(){el('#settings').classList.toggle('open')};el('#apiBase').value=sessionStorage.getItem('robertaApiBase')||'';el('#apiKey').value=sessionStorage.getItem('robertaApiKey')||'';el('#apiBase').onchange=function(){sessionStorage.setItem('robertaApiBase',this.value.trim());health()};el('#apiKey').onchange=function(){sessionStorage.setItem('robertaApiKey',this.value);health()};
</script>
</body></html>'''


def web_ui_bytes() -> bytes:
    return ROBERTA_WEB_UI_HTML.encode("utf-8")


__all__ = ["ROBERTA_WEB_UI_HTML", "web_ui_bytes"]
