"""Evidence-grounded Roberta Learning System boundaries."""

from .chunking import (
    CHUNKER_CONTRACT,
    ChunkedDocument,
    ChunkingError,
    ChunkManifest,
    EvidenceChunk,
    chunk_parsed_document,
)
from .indexing import (
    INDEX_CONTRACT,
    LEXICAL_ANALYZER_CONTRACT,
    DeterministicHashEmbeddingProvider,
    EmbeddingIndexEntry,
    EmbeddingProvider,
    EmbeddingProviderInfo,
    EmbeddingRequest,
    EmbeddingResult,
    IndexedDocument,
    IndexingError,
    IndexManifest,
    LexicalIndexEntry,
    build_evidence_index,
)
from .source_ingestion import (
    InMemorySourceStore,
    IngestionResult,
    SourceIngestionError,
    SourceRecord,
    SourceStore,
    ingest_utf8_source,
)
from .structure import (
    PARSER_CONTRACT,
    DocumentRecord,
    ParsedDocument,
    SectionRecord,
    StructuralBlock,
    StructureParseError,
    parse_markdown_structure,
)

__all__ = [
    "CHUNKER_CONTRACT",
    "INDEX_CONTRACT",
    "LEXICAL_ANALYZER_CONTRACT",
    "ChunkManifest",
    "ChunkedDocument",
    "ChunkingError",
    "DeterministicHashEmbeddingProvider",
    "DocumentRecord",
    "EmbeddingIndexEntry",
    "EmbeddingProvider",
    "EmbeddingProviderInfo",
    "EmbeddingRequest",
    "EmbeddingResult",
    "EvidenceChunk",
    "IndexedDocument",
    "IndexingError",
    "IndexManifest",
    "InMemorySourceStore",
    "IngestionResult",
    "LexicalIndexEntry",
    "PARSER_CONTRACT",
    "ParsedDocument",
    "SectionRecord",
    "SourceIngestionError",
    "SourceRecord",
    "SourceStore",
    "StructuralBlock",
    "StructureParseError",
    "build_evidence_index",
    "chunk_parsed_document",
    "ingest_utf8_source",
    "parse_markdown_structure",
]
